[package]
name = "deeprust"
version = "0.1.0"
authors = ["Patrick Haas <patmanteau@posteo.de>"]

[dependencies]
log = "0.3.8"
simple-logging = "1.0.1"
indoc = "0.2"
clap = "2.27.1"
unicode-segmentation = "1.2.0"
bitwise = "0.1.1"